Remove phone param for `editTxn`
AY2425S1-CS2103-F13-1/tp pull request #481
Opened 2024-11-09 16:26 UTC by seanlim

Closes #446 by softly removing parsing for phone number in the `editTxn` command.

2024-11-09 16:30 UTC, SeeYangZhi requested changes
Corresponding DG/UG should be changed

2024-11-09 16:32 UTC, seanlim commented
No mention of `p/` in DG

2024-11-10 05:09 UTC, rollingpencil approved these changes
LGTM

2024-11-10 05:27 UTC, SeeYangZhi approved these changes

2024-11-10 05:27 UTC, merged